#!/usr/bin/env python

'''
I don't feel like makeing a rekey (password change) dialog at the moment.
To change the password, open python terminal
>>> import SecretKeeper
>>> SecretKeeper.rekey('old_key', 'new_key')
'''

#default key (password) = 'nicol'
geometry = "600x500+300+300" #default

import Tkinter as tk
import ttk
from ScrolledText import ScrolledText
from sys import argv
import random

RAND_LENGTH = 4 # number of words in the random password generator
LATEST = 1 # simplecrypt version. version 2 is better but I prefer speed over security. Change anytime.

###### stolen from simplecrypt; see https://pypi.python.org/pypi/simple-crypt #####

try:
	from Crypto.Cipher import AES
	from Crypto.Hash import SHA256, HMAC
	from Crypto.Protocol.KDF import PBKDF2
	from Crypto.Random.random import getrandbits
	from Crypto.Util import Counter
except ImportError:
	tk.Tk().withdraw()
	from tkMessageBox import showerror
	showerror("Modules Missing", "pycrypto is not installed. Run this command to install pycrypto:\n\nsudo pip install pycrypto")
	raise

# see: http://www.daemonology.net/blog/2009-06-11-cryptographic-right-answers.html

EXPANSION_COUNT = (10000, 10000, 100000)
AES_KEY_LEN = 256
SALT_LEN = (128, 256, 256)
HASH = SHA256
PREFIX = b'sc'
HEADER = (PREFIX + b'\x00\x00', PREFIX + b'\x00\x01', PREFIX + b'\x00\x02')

# lengths here are in bits, but pcrypto uses block size in bytes
HALF_BLOCK = AES.block_size*8//2
for salt_len in SALT_LEN:
	assert HALF_BLOCK <= salt_len  # we use a subset of the salt as nonce

HEADER_LEN = 4
for header in HEADER:
	assert len(header) == HEADER_LEN

def encrypt(password, data):
	'''
	Encrypt some data.  Input can be bytes or a string (which will be encoded
	using UTF-8).

	@param password: The secret value used as the basis for a key.
	This should be as long as varied as possible.  Try to avoid common words.

	@param data: The data to be encrypted.

	@return: The encrypted data, as bytes.
	'''
	data = _str_to_bytes(data)
	_assert_encrypt_length(data)
	salt = bytes(_random_bytes(SALT_LEN[LATEST]//8))
	hmac_key, cipher_key = _expand_keys(password, salt, EXPANSION_COUNT[LATEST])
	counter = Counter.new(HALF_BLOCK, prefix=salt[:HALF_BLOCK//8])
	cipher = AES.new(cipher_key, AES.MODE_CTR, counter=counter)
	encrypted = cipher.encrypt(data)
	hmac = _hmac(hmac_key, HEADER[LATEST] + salt + encrypted)
	output = HEADER[LATEST] + salt + encrypted + hmac
	return output.encode('base64')


def decrypt(password, data):
	'''
	Decrypt some data.  Input must be bytes.

	@param password: The secret value used as the basis for a key.
	This should be as long as varied as possible.  Try to avoid common words.

	@param data: The data to be decrypted, typically as bytes.

	@return: The decrypted data, as bytes.  If the original message was a
	string you can re-create that using `result.decode('utf8')`.
	'''
	data = data.decode('base64')
	_assert_not_unicode(data)
	_assert_header_prefix(data)
	version = _assert_header_version(data)
	_assert_decrypt_length(data, version)
	raw = data[HEADER_LEN:]
	salt = raw[:SALT_LEN[version]//8]
	hmac_key, cipher_key = _expand_keys(password, salt, EXPANSION_COUNT[version])
	hmac = raw[-HASH.digest_size:]
	hmac2 = _hmac(hmac_key, data[:-HASH.digest_size])
	_assert_hmac(hmac_key, hmac, hmac2)
	counter = Counter.new(HALF_BLOCK, prefix=salt[:HALF_BLOCK//8])
	cipher = AES.new(cipher_key, AES.MODE_CTR, counter=counter)
	return cipher.decrypt(raw[SALT_LEN[version]//8:-HASH.digest_size])

class DecryptionException(Exception): pass
class EncryptionException(Exception): pass

def _assert_not_unicode(data):
	# warn confused users
	u_type = type(b''.decode('utf8'))
	if isinstance(data, u_type):
		raise DecryptionException('Data to decrypt must be bytes; ' +
		'you cannot use a string because no string encoding will accept all possible characters.')

def _assert_encrypt_length(data):
	# for AES this is never going to fail
	if len(data) > 2**HALF_BLOCK:
		raise EncryptionException('Message too long.')

def _assert_decrypt_length(data, version):
	if len(data) < HEADER_LEN + SALT_LEN[version]//8 + HASH.digest_size:
		raise DecryptionException('Missing data.')

def _assert_header_prefix(data):
	if len(data) >= 2 and data[:2] != PREFIX:
		raise DecryptionException('Data passed to decrypt were not generated by simple-crypt (bad header).')

def _assert_header_version(data):
	if len(data) >= HEADER_LEN:
		try:
			return HEADER.index(data[:HEADER_LEN])
		except:
			raise DecryptionException(
				'The data appear to be encrypted with a more recent version of simple-crypt (bad header). ' +
				'Please update the library and try again.')
	else:
		raise DecryptionException('Missing header.')

def _assert_hmac(key, hmac, hmac2):
	# https://www.isecpartners.com/news-events/news/2011/february/double-hmac-verification.aspx
	if _hmac(key, hmac) != _hmac(key, hmac2):
		raise DecryptionException('Bad password or corrupt / modified data.')

def _pbkdf2(password, salt, n_bytes, count):
	# the form of the prf below is taken from the code for PBKDF2
	return PBKDF2(password, salt, dkLen=n_bytes,
				  count=count, prf=lambda p,s: HMAC.new(p,s,HASH).digest())

def _expand_keys(password, salt, expansion_count):
	if not salt: raise ValueError('Missing salt.')
	if not password: raise ValueError('Missing password.')
	key_len = AES_KEY_LEN // 8
	keys = _pbkdf2(_str_to_bytes(password), salt, 2*key_len, expansion_count)
	return keys[:key_len], keys[key_len:]

def _hide(ranbytes):
	# appelbaum recommends obscuring output from random number generators since it can reveal state.
	# we can do this explicitly with a hash, but this is what a PBKDF does anyway, so use one.
	# we don't care about the salt or work factor because there is a large space of values anyway.
	return bytearray(_pbkdf2(bytes(ranbytes), b'', len(ranbytes), 1))

def _random_bytes(n):
	return _hide(bytearray(getrandbits(8) for _ in range(n)))

def _hmac(key, data):
	return HMAC.new(key, data, HASH).digest()

def _str_to_bytes(data):
	u_type = type(b''.decode('utf8'))
	if isinstance(data, u_type):
		return data.encode('utf8')
	return data

##### end simplecrypt thievery #####

#default key (password) = 'nicol'
data = 'ZxpLVPJD43PjTJsBma4YpmdqLFF8LcMJv4q2fXH/SeaRFg==' #default

data_delim = ' '.join(('####dammed','data####\n'))
geometry = "400x500+300+300" #default
title = "Very Secret Things"

def save(new_data, key, new_geo=None):
	'''encrypt and save new data to this file
	new_data is an unencrypted string
	optionally provide a new geometry string'''
	global data #technically not needed in GUI mode since this function is called only when quitting
	fn = __file__
	if fn.endswith('.pyc'):
		fn = fn[:-1] #if the file is compiled, change the .py file.
	with open(fn, "r+") as f:
		contents = f.read().split(data_delim)
		if len(contents) != 3:
			raise TypeError, "File is not of the right type"
		data = encrypt(key, new_data)
		contents[1] = "geometry=%s\n" % repr(new_geo or geometry)
		contents[1] += "title=%s\n" % repr(title)
		contents[1] += "data='''\n%s'''\n" % data
		#erase file and write new contents
		f.seek(0)
		f.truncate()
		f.write(data_delim.join(contents))

def rekey(old_key, new_key):
	'''change key for the global data'''
	secret = decrypt(old_key,data)
	save(secret, new_key)

class Window(ttk.Frame):
	def __init__(self, parent):
		self.tab_delim = "\n=====++++++=====\n"
		self.tabs = []
		self.dirty = False

		ttk.Frame.__init__(self, parent)
		self.parent = parent
		self.parent.title(title)
		self.style = ttk.Style()
		self.style.theme_use("default")
		self.pack(fill=tk.BOTH, expand=1)
		self.nb = ttk.Notebook(self)
		self.nb.pack(fill=tk.BOTH, expand=1)

		self.saveButton = ttk.Button(self, text="Close", command=self.save)
		self.saveButton.pack(side=tk.RIGHT, padx=5, pady=5)
		# I don't feel like making a rekey dialog atm
		#~ rekeyButton = ttk.Button(self, text="Re-Key", command=self.rekey)
		#~ rekeyButton.pack(side=tk.RIGHT, padx=5, pady=5)
		addButton = ttk.Button(self, text="Add Tab", command=self.add_tab)
		addButton.pack(side=tk.LEFT, padx=5, pady=5)
		delButton = ttk.Button(self, text="Delete Tab", command=self.rem_tab)
		delButton.pack(side=tk.LEFT, padx=5, pady=5)
		passButton = ttk.Button(self, text="new password", command=self.randpass)
		passButton.pack(side=tk.LEFT, padx=5, pady=5)
		self.randpass_ent = tk.Entry(self, width=30)
		self.randpass_ent.pack(side=tk.LEFT, padx=5, pady=5)

		#add search tab
		f = ttk.Frame(self.nb)
		self.search = ttk.Entry(f)
		self.search.focus()
		self.search.pack(fill=tk.BOTH)
		self.search.bind("<KeyRelease>", self.search_key_press)
		self.search_result = ScrolledText(f, relief=tk.RAISED, wrap=tk.WORD, state=tk.DISABLED)
		self.search_result.pack(fill=tk.BOTH, expand=1)
		self.nb.add(f, text='search')

		#add other tabs
		for text in self.parent.secret.split(self.tab_delim):
			self.add_tab(text, dirty=False)
		self.nb.select(self.nb.tabs()[0]) #select search tab

		self.dictionary = dictionary.split()
		self.randpass()

		parent.geometry(geometry)
		parent.minsize(600, 460)

	def randpass(self):
		self.randpass_ent.delete(0, tk.END)
		self.randpass_ent.insert(0, ' '.join(random.choice(self.dictionary) for _ in range(RAND_LENGTH)))

	def search_key_press(self, key):
		'''if search key is found displays that line and all lines below
		it until an empty line is reached.'''
		search = self.search.get()
		found = []
		state = None
		for line in self.parent.secret.splitlines():
			if state is None:
				if search in line.lower():
					state = line
			else:
				if line.strip() == "":
					found.append(state)
					state = None
				else:
					state += "\n"+line
		if state is not None:
			found.append(state)
		self.search_result.config(state=tk.NORMAL)
		self.search_result.delete("0.0", tk.END)
		self.search_result.insert(tk.INSERT, "\n\n".join(found))
		self.search_result.config(state=tk.DISABLED)

	def save(self):
		if self.dirty: #file changed, update secret before saving
			self.update(dirty=False)
			save(self.parent.secret, self.parent.key, self.parent.geometry())
		self.quit()

	def rem_tab(self):
		tabid = self.nb.select()
		if self.nb.index(tabid) > 0:
			#index minus 1 to account for search tab
			del self.tabs[self.nb.index(tabid)-1]
			self.nb.forget(tabid)
			self.update()

	def add_tab(self, text='new', dirty=True):
		f = ttk.Frame(self.nb)
		# see http://stackoverflow.com/questions/13832720/how-to-attach-a-scrollbar-to-a-text-widget
		t = ScrolledText(f, relief=tk.RAISED, wrap=tk.WORD)
		t.insert(tk.INSERT, text)
		t.pack(fill=tk.BOTH, expand=1)
		t.bind("<KeyRelease>", self.update)
		self.nb.add(f)
		self.tabs.append(t)
		self.nb.select(self.nb.tabs()[-1])
		self.update(dirty=dirty)

	def update(self, key=None, dirty=True):
		if dirty and not self.dirty:
			self.dirty = True
			self.saveButton.config(text="Save&Close")
		data = [tab.get('0.0', tk.END).rstrip() for tab in self.tabs]
		self.parent.secret = self.tab_delim.join(data)
		#update tab title
		tabid = self.nb.select()
		name = data[self.nb.index(tabid)-1].rstrip().split('\n',1)[0].strip()
		self.nb.tab(tabid, text=name or "empty")

class PasswordDialog(ttk.Frame):
	def __init__(self, parent):
		ttk.Frame.__init__(self, parent)
		self.parent = parent

		self.parent.title("Password")
		self.style = ttk.Style()
		self.style.theme_use("default")
		self.pack(fill=tk.BOTH, expand=1)

		self.label = ttk.Label(self, text="Enter your Password")
		self.label.pack()
		self.entry = ttk.Entry(self, show='*')
		self.entry.bind("<KeyRelease-Return>", self.store_pass)
		self.entry.pack()
		self.entry.focus()
		button = ttk.Button(self, text="Submit", command=self.store_pass)
		button.pack()

	def store_pass(self, event=None):
		self.parent.key = self.entry.get()
		if self.parent.key == "":
			self.quit() #user entered nothing; treat as user cancel
		try:
			self.parent.secret = decrypt(self.parent.key,data)
			self.destroy()
			app = Window(self.parent)
		except DecryptionException:
			self.label.config(text = "Wrong Password", foreground="red")
			self.entry.delete(0, tk.END)

def main(password=None):
	root = tk.Tk()
	if password:
		root.secret = decrypt(password,data)
		root.key = password
		app = Window(root)
	else:
		app = PasswordDialog(root)
	root.mainloop()

dictionary = '''
aaron abandoned aberdeen abilities ability aboriginal abortion about above abraham abroad absence
absent absolute absolutely absorption abstract abstracts abuse academic academics academy accent
accept acceptable acceptance accepted accepting accepts access accessed accessibility accessible
accessing accessories accessory accident accidents accommodate accommodation accommodations
accompanied accompanying accomplish accomplished accordance according accordingly account
accountability accounting accounts accreditation accredited accuracy accurate accurately accused
acdbentity achieve achieved achievement achievements achieving acids acknowledge acknowledged
acoustic acquire acquired acquisition acquisitions acres acrobat across acrylic acting action
actions activated activation active actively activists activities activity actor actors actress
actual actually acute adams adaptation adapted adapter adapters adaptive adaptor added addiction
adding addition additional additionally additions address addressed addresses addressing adelaide
adequate adidas adipex adjacent adjust adjustable adjusted adjustment adjustments admin administered
administration administrative administrator administrators admission admissions admit admitted adobe
adolescent adopt adopted adoption adrian adult adults advance advanced advancement advances
advantage advantages adventure adventures adverse advert advertise advertisement advertisements
advertiser advertisers advertising advice advise advised advisor advisors advisory advocacy advocate
adware aerial aerospace affair affairs affect affected affecting affects affiliate affiliated
affiliates affiliation afford affordable afghanistan afraid africa african after afternoon
afterwards again against agencies agency agenda agent agents aggregate aggressive aging agree agreed
agreement agreements agrees agricultural agriculture ahead aimed aircraft airfare airline airlines
airplane airport airports alabama alarm alaska albania albany albert alberta album albums
albuquerque alcohol alert alerts alexander alexandria alfred algebra algeria algorithm algorithms
alias alice alien align alignment alike alive allah allan alleged allen allergy alliance allied
allocated allocation allow allowance allowed allowing allows alloy almost alone along alpha
alphabetical alpine already alter altered alternate alternative alternatively alternatives although
aluminium aluminum alumni always amanda amateur amazing amazon amazoncom amazoncouk ambassador amber
ambien ambient amend amended amendment amendments amenities america american americans americas
amino among amongst amount amounts ampland amplifier amsterdam anaheim analog analyses analysis
analyst analysts analytical analyze analyzed anatomy anchor ancient andale anderson andorra andrea
andreas andrew andrews angel angela angeles angels anger angle angola angry animal animals animated
animation anime annex annie anniversary annotated annotation announce announced announcement
announcements announces annoying annual annually anonymous another answer answered answering answers
antarctica antenna anthony anthropology antibodies antibody anticipated antigua antique antiques
antivirus antonio anxiety anybody anymore anyone anything anytime anyway anywhere apache apart
apartment apartments apnic apollo apparatus apparel apparent apparently appeal appeals appear
appearance appeared appearing appears appendix apple appliance appliances applicable applicant
applicants application applications applied applies apply applying appointed appointment
appointments appraisal appreciate appreciated appreciation approach approaches appropriate
appropriations approval approve approved approx approximate approximately april aquarium aquatic
arabia arabic arbitrary arbitration arcade architect architects architectural architecture archive
archived archives arctic areas arena argentina argue argued argument arguments arise arising arizona
arkansas arlington armed armenia armor armstrong arnold around arrange arranged arrangement
arrangements array arrest arrested arrival arrivals arrive arrived arrives arrow arthritis arthur
article articles artificial artist artistic artists artwork aruba asbestos ascii ashley asian aside
asked asking aspect aspects aspnet assault assembled assembly assess assessed assessing assessment
assessments asset assets assign assigned assignment assignments assist assistance assistant assisted
assists associate associated associates association associations assume assumed assumes assuming
assumption assumptions assurance assure assured asthma astrology astronomy athens athletes athletic
athletics atlanta atlantic atlas atmosphere atmospheric atomic attach attached attachment
attachments attack attacked attacks attempt attempted attempting attempts attend attendance attended
attending attention attitude attitudes attorney attorneys attract attraction attractions attractive
attribute attributes auburn auckland auction auctions audience audio audit auditor august aurora
austin australia australian austria authentic authentication author authorities authority
authorization authorized authors automated automatic automatically automation automobile automobiles
automotive autos autumn availability available avatar avenue average aviation avoid avoiding award
awarded awards aware awareness awesome awful azerbaijan babes babies bachelor backed background
backgrounds backing backup bacon bacteria bacterial badge badly baghdad bahamas bahrain bailey baker
baking balance balanced ballet balloon ballot balls baltimore banana bands bandwidth bangbus bangkok
bangladesh banking bankruptcy banks banned banner banners baptist barbados barbara barbie barcelona
barely bargain bargains barnes barrel barrier barriers barry baseball based baseline basement
basename bases basic basically basics basin basis basket basketball baskets batch bathroom bathrooms
baths batman batteries battery battle battlefield beach beaches beads beans bearing bears beast
beastality beastiality beatles beats beautiful beautifully beauty beaver became because become
becomes becoming bedding bedford bedroom bedrooms before began begin beginner beginners beginning
begins begun behalf behavior behavioral behaviour behind beijing being beings belarus belfast
belgium belief beliefs believe believed believes belize belkin belle belly belong belongs below
belts bench benchmark beneath beneficial benefit benefits benjamin bennett berkeley berlin bermuda
bernard berry beside besides bestiality bestsellers better betting betty between beverage beverages
beverly beyond bhutan bible biblical bibliographic bibliography bicycle bidder bidding bigger
biggest bikes bikini billing billion bills billy binary binding bingo biodiversity biographies
biography biological biology biotechnology birds birmingham birth birthday bishop bitch bizarre
bizrate black blackberry blackjack blacks blade blades blair blake blame blank blanket blast
bleeding blend bless blessed blind blink block blocked blocking blocks blogger bloggers blogging
blogs blond blonde blood bloody bloom bloomberg blowing blowjob blowjobs blues bluetooth board
boards boating boats bobby bodies bolivia bondage bonds bones bonus boobs booking bookings bookmark
bookmarks books bookstore boolean boost booth boots booty border borders bored boring borough bosnia
boston bother botswana bottle bottles bottom bought boulder boulevard bound boundaries boundary
bouquet boutique bowling boxed boxes boxing bracelet bracelets bracket bradford bradley brain brake
brakes branch branches brand brandon brands brass brave brazil brazilian breach bread break
breakdown breakfast breaking breaks breast breasts breath breathing breed breeding breeds brian
brick bridal bride bridge bridges brief briefing briefly briefs bright brighton brilliant bring
bringing brings brisbane bristol britain britannica british britney broad broadband broadcast
broadcasting broader broadway brochure brochures broke broken broker brokers bronze brook brooklyn
brooks brother brothers brought brown browse browser browsers browsing bruce brunei brunette
brunswick brush brussels brutal bryan bryant bubble bucks budapest buddy budget budgets buffalo
buffer bufing build builder builders building buildings builds built bukkake bulgaria bulgarian
bullet bulletin bumper bunch bundle bunny burden bureau buried burke burlington burner burning burns
burst burton buses business businesses busty butler butter butterfly button buttons butts buyer
buyers buying bytes cabin cabinet cabinets cable cables cache cached cadillac cakes calcium
calculate calculated calculation calculations calculator calculators calendar calendars calgary
calibration calif california called calling calls calvin cambodia cambridge camcorder camcorders
camel camera cameras cameron cameroon campaign campaigns campbell camping camps campus canada
canadian canal canberra cancel cancellation cancelled cancer candidate candidates candle candles
candy cannon canon canvas canyon capabilities capability capable capacity capital capitol captain
capture captured carbon cardiac cardiff cardiovascular cards career careers careful carefully carey
cargo caribbean caring carlo carlos carmen carnival carol carolina caroline carpet carried carrier
carriers carries carroll carry carrying carter cartoon cartoons cartridge cartridges cases casey
cashiers casino casinos casio cassette casting castle casual catalog catalogs catalogue catalyst
catch categories category catering cathedral catherine catholic cattle caught cause caused causes
causing caution cayman cedar ceiling celebrate celebration celebrities celebrity celebs cells
cellular celtic cement cemetery census center centered centers central centre centres cents
centuries century ceramic ceremony certain certainly certificate certificates certification
certified chain chains chair chairman chairs challenge challenged challenges challenging chamber
chambers champagne champion champions championship championships chance chancellor chances change
changed changelog changes changing channel channels chaos chapel chapter chapters character
characteristic characteristics characterization characterized characters charge charged charger
chargers charges charging charitable charity charles charleston charlie charlotte charm charming
charms chart charter charts chase chassis cheap cheaper cheapest cheat cheats check checked checking
checklist checkout checks cheers cheese chelsea chemical chemicals chemistry cheque cherry chess
chest chester chevrolet chevy chicago chick chicken chicks chief child childhood children childrens
chile china chinese chips chocolate choice choices choir cholesterol choose choosing chorus chose
chosen chris christ christian christianity christians christina christine christmas christopher
chrome chronic chronicle chronicles chrysler chubby chuck church churches cialis cigarette
cigarettes cincinnati cindy cinema cingular circle circles circuit circuits circular circulation
circumstances circus cisco citation citations cited cities citizen citizens citizenship citysearch
civic civil civilian civilization claim claimed claims claire clara clarity clark clarke class
classes classic classical classics classification classified classifieds classroom clause clean
cleaner cleaners cleaning cleanup clear clearance cleared clearing clearly clerk cleveland click
clicking clicks client clients cliff climate climb climbing clinic clinical clinics clinton clips
clock clocks clone close closed closely closer closes closest closing closure cloth clothes clothing
cloud clouds cloudy clubs cluster clusters cnetcom coach coaches coaching coalition coast coastal
coated coating cocks codes coding coffee cognitive cohen coins coleman colin collaboration
collaborative collapse collar colleague colleagues collect collectables collected collectible
collectibles collecting collection collections collective collector collectors college colleges
collins cologne colombia colon colonial colony color colorado colored colors colour colours columbia
columbus column columnists columns combat combination combinations combine combined combines
combining combo comedy comes comfort comfortable comic comics coming command commander commands
comment commentary commented comments commerce commercial commission commissioner commissioners
commissions commit commitment commitments committed committee committees commodities commodity
common commonly commons commonwealth communicate communication communications communist communities
community compact companies companion company compaq comparable comparative compare compared
comparing comparison comparisons compatibility compatible compensation compete competent competing
competition competitions competitive competitors compilation compile compiled compiler complaint
complaints complement complete completed completely completing completion complex complexity
compliance compliant complicated complications complimentary comply component components composed
composer composite composition compound compounds comprehensive compressed compression compromise
computation computational compute computed computer computers computing concentrate concentration
concentrations concept concepts conceptual concern concerned concerning concerns concert concerts
conclude concluded conclusion conclusions concord concrete condition conditional conditioning
conditions condo condos conduct conducted conducting conference conferences conferencing confidence
confident confidential confidentiality config configuration configure configured configuring confirm
confirmation confirmed conflict conflicts confused confusion congo congratulations congress
congressional conjunction connect connected connecticut connecting connection connections
connectivity connector connectors conscious consciousness consecutive consensus consent consequence
consequences consequently conservation conservative consider considerable consideration
considerations considered considering considers consist consistency consistent consistently
consisting consists console consoles consolidated consolidation consortium conspiracy const constant
constantly constitute constitutes constitution constitutional constraint constraints construct
constructed construction consult consultancy consultant consultants consultation consulting consumer
consumers consumption contact contacted contacting contacts contain contained container containers
containing contains contamination contemporary content contents contest contests context continent
continental continually continue continued continues continuing continuity continuous continuously
contract contracting contractor contractors contracts contrary contrast contribute contributed
contributing contribution contributions contributor contributors control controlled controller
controllers controlling controls controversial controversy convenience convenient convention
conventional conventions convergence conversation conversations conversion convert converted
converter convertible convicted conviction convinced cookbook cooked cookie cookies cooking cooler
cooling cooper cooperation cooperative coordinate coordinated coordinates coordination coordinator
copied copies copper copying copyright copyrighted copyrights coral cordless cornell corner corners
cornwall corporate corporation corporations corps corpus correct corrected correction corrections
correctly correlation correspondence corresponding corruption cosmetic cosmetics costa costs costume
costumes cottage cottages cotton could council councils counsel counseling count counted counter
counters counties counting countries country counts county couple coupled couples coupon coupons
courage courier course courses court courtesy courts cover coverage covered covering covers cowboy
crack cradle craft crafts craig craps crash crawford crazy cream create created creates creating
creation creations creative creativity creator creature creatures credit credits creek crest cricket
crime crimes criminal crisis criteria criterion critical criticism critics croatia crops cross
crossing crossword crowd crown crucial crude cruise cruises crystal cubic cuisine cultural culture
cultures cumshot cumshots cumulative curious currencies currency current currently curriculum cursor
curtis curve curves custody custom customer customers customise customize customized customs cutting
cyber cycle cycles cycling cylinder cyprus czech daddy daily dairy daisy dakota dallas damage
damaged damages dance dancing danger dangerous daniel danish danny darkness darwin database
databases dated dates dating daughter daughters david davidson davis dayton deadline deadly dealer
dealers dealing deals dealt dealtime death deaths debate debian deborah debug debut decade decades
december decent decide decided decimal decision decisions declaration declare declared decline
declined decor decorating decorative decrease decreased dedicated deemed deeper deeply default
defeat defects defence defend defendant defense defensive deferred deficit define defined defines
defining definitely definition definitions degree degrees delaware delay delayed delays delegation
delete deleted delhi delicious delight deliver delivered delivering delivers delivery delta deluxe
demand demanding demands democracy democrat democratic democrats demographic demonstrate
demonstrated demonstrates demonstration denial denied denmark dennis dense density dental dentists
denver department departmental departments departure depend dependence dependent depending depends
deployment deposit deposits depot depression depth deputy derby derek derived descending describe
described describes describing description descriptions desert deserve design designated designation
designed designer designers designing designs desirable desire desired desktop desktops desperate
despite destination destinations destiny destroy destroyed destruction detail detailed details
detect detected detection detective detector determination determine determined determines
determining detroit deutsch deutsche deutschland devel develop developed developer developers
developing development developmental developments develops deviant deviation device devices devil
devon devoted diabetes diagnosis diagnostic diagram dialog dialogue diameter diamond diamonds diana
diane diary dicke dicks dictionaries dictionary diego diesel dietary differ difference differences
different differential differently difficult difficulties difficulty diffs digest digit digital
dildo dildos dimension dimensional dimensions dining dinner diploma direct directed direction
directions directive directly director directories directors directory dirty disabilities disability
disable disabled disagree disappointed disaster discharge disciplinary discipline disciplines
disclaimer disclaimers disclose disclosure disco discount discounted discounts discover discovered
discovery discrete discretion discrimination discs discuss discussed discusses discussing discussion
discussions disease diseases dishes disks disney disorder disorders dispatch dispatched display
displayed displaying displays disposal disposition dispute disputes distance distances distant
distinct distinction distinguished distribute distributed distribution distributions distributor
distributors district districts disturbed diverse diversity divide divided dividend divine diving
division divisions divorce doctor doctors doctrine document documentary documentation
documentcreatetextnode documented documents dodge doing dollar dollars dolls domain domains domestic
dominant dominican donald donate donated donation donations donna donor donors doors dosage double
doubt douglas dover download downloadable downloadcom downloaded downloading downloads downtown
dozen dozens draft dragon drain drainage drama dramatic dramatically drawing drawings drawn draws
dream dreams dress dressed dresses dressing dried drill drilling drink drinking drinks drive driven
driver drivers drives driving dropped drops drove drugs drums drunk dryer dubai dublin duncan
duplicate durable duration durham during dutch duties dying dylan dynamic dynamics eagle eagles
earlier earliest early earned earning earnings earrings earth earthquake easier easily easter
eastern eating ebony ebook ebooks eclipse ecological ecology ecommerce economic economics economies
economy ecuador eddie edgar edges edinburgh edited editing edition editions editor editorial
editorials editors edmonton educated education educational educators edward edwards effect effective
effectively effectiveness effects efficiency efficient efficiently effort efforts egypt egyptian
eight either ejaculation elder elderly elect elected election elections electoral electric
electrical electricity electro electron electronic electronics elegant element elementary elements
elephant elevation eleven eligibility eligible eliminate elimination elite elizabeth ellen elliott
ellis elsewhere elvis emacs email emails embassy embedded emerald emergency emerging emily eminem
emirates emission emissions emotional emotions emperor emphasis empire empirical employ employed
employee employees employer employers employment empty enable enabled enables enabling enclosed
enclosure encoding encounter encountered encourage encouraged encourages encouraging encryption
encyclopedia endangered ended endif ending endless endorsed endorsement enemies enemy energy
enforcement engage engaged engagement engaging engine engineer engineering engineers engines england
english enhance enhanced enhancement enhancements enhancing enjoy enjoyed enjoying enlarge
enlargement enormous enough enquiries enquiry enrolled enrollment ensemble ensure ensures ensuring
enter entered entering enterprise enterprises enters entertaining entertainment entire entirely
entities entitled entity entrance entrepreneur entrepreneurs entries entry envelope environment
environmental environments enzyme epinions epinionscom episode episodes epson equal equality equally
equation equations equilibrium equipment equipped equity equivalent ericsson erotic erotica error
errors escape escort escorts especially essay essays essence essential essentially essentials essex
establish established establishing establishment estate estates estimate estimated estimates
estimation estonia eternal ethernet ethical ethics ethiopia ethnic eugene europe european euros
evaluate evaluated evaluating evaluation evaluations evanescence evans evening event events
eventually every everybody everyday everyone everything everywhere evidence evident evolution exact
exactly examination examinations examine examined examines examining example examples exams exceed
excel excellence excellent except exception exceptional exceptions excerpt excess excessive exchange
exchanges excited excitement exciting exclude excluded excluding exclusion exclusive exclusively
excuse execute executed execution executive executives exempt exemption exercise exercises exhaust
exhibit exhibition exhibitions exhibits exist existed existence existing exists exotic expand
expanded expanding expansion expansys expect expectations expected expects expedia expenditure
expenditures expense expenses expensive experience experienced experiences experiencing experiment
experimental experiments expert expertise experts expiration expired expires explain explained
explaining explains explanation explicit explicitly exploration explore explorer exploring explosion
export exports exposed exposure express expressed expression expressions extend extended extending
extends extension extensions extensive extent exterior external extra extract extraction
extraordinary extras extreme extremely fabric fabrics fabulous faced faces facial facilitate
facilities facility facing factor factors factory facts faculty failed failing fails failure
failures fairfield fairly fairy faith fallen falling falls false familiar families family famous
fancy fantastic fantasy fares farmer farmers farming farms fascinating fashion faster fastest fatal
father fathers fatty fault favor favorite favorites favors favour favourite favourites fears feature
featured features featuring february federal federation feedback feeding feeds feeling feelings
feels fellow fellowship female females fence ferrari ferry festival festivals fetish fever fewer
fiber fibre fiction field fields fifteen fifth fifty fight fighter fighters fighting figure figured
figures filed filename files filing filled filling filme films filter filtering filters final
finally finals finance finances financial financing findarticles finder finding findings findlaw
finds finest finger fingering fingers finish finished finishing finite finland finnish fioricet
fired firefox fireplace fires firewall firewire firms firmware first fiscal fisher fisheries fishing
fisting fitness fitted fitting fixed fixes fixtures flags flame flash flashers flashing flavor
fleece fleet flesh flexibility flexible flickr flight flights float floating flood floor flooring
floors floppy floral florence florida florist florists flour flower flowers flows floyd fluid flush
flyer flying focal focus focused focuses focusing folder folders folding folks follow followed
following follows fonts foods footage football footwear forbes forbidden force forced forces
forecast forecasts foreign forest forestry forests forever forge forget forgot forgotten formal
format formation formats formatting formed former formerly forming forms formula forth fortune forty
forum forums forward forwarding fossil foster fotos fought found foundation foundations founded
founder fountain fourth fraction fragrance fragrances frame framed frames framework framing france
franchise francis francisco frank frankfurt franklin fraser fraud frederick freebsd freedom
freelance freely freeware freeze freight french frequencies frequency frequent frequently fresh
friday fridge friend friendly friends friendship front frontier frontpage frost frozen fruit fruits
fucked fucking fujitsu fully function functional functionality functioning functions fundamental
fundamentals funded funding fundraising funds funeral funky funny furnished furnishings furniture
further furthermore fusion future futures fuzzy gabriel gadgets gained gains galaxy galleries
gallery gambling gamecube games gamespot gaming gamma gangbang garage garbage garcia garden
gardening gardens garlic garmin gasoline gates gateway gather gathered gathering gauge gazette
gender genealogy general generally generate generated generates generating generation generations
generator generators generic generous genes genesis genetic genetics geneva genius genome genre
genres gentle gentleman gently genuine geographic geographical geography geological geology geometry
george georgia gerald german germany getting ghana ghost giant giants gibraltar gibson gifts gilbert
girlfriend girls given gives giving glance glasgow glass glasses glenn global globe glory glossary
gloves glucose gnome goals going golden gonna goods google gordon gorgeous gospel gossip gothic
gotta gotten gourmet governance governing government governmental governments governor grace grade
grades gradually graduate graduated graduates graduation graham grain grammar grams grand grande
granny grant granted grants graph graphic graphical graphics graphs grass grateful gratis gratuit
grave gravity great greater greatest greatly greece greek green greene greenhouse greensboro
greeting greetings gregory grenada griffin grill grocery groove gross ground grounds groundwater
group groups grove growing grown grows growth guarantee guaranteed guarantees guard guardian guards
guatemala guess guest guestbook guests guidance guide guided guidelines guides guild guilty guinea
guitar guitars guyana habitat habits hacker hairy haiti halfcom halifax halloween hamburg hamilton
hammer hampshire hampton handbags handbook handed handheld handhelds handjob handjobs handle handled
handles handling handmade hands handy hanging hansen happen happened happening happens happiness
happy harassment harbor harbour hardcore hardcover harder hardly hardware hardwood harley harmful
harmony harold harper harris harrison harry hartford harvard harvest harvey haven having hawaii
hawaiian hayes hazard hazardous hazards headed header headers heading headline headlines headphones
headquarters heads headset healing health healthcare healthy heard hearing hearings heart hearts
heated heater heath heather heating heaven heavily heavy hebrew height heights helen helena
helicopter hello helmet helped helpful helping helps hence henderson henry hentai hepatitis herald
herbal herbs hereby herein heritage heroes herself hewlett hidden hierarchy higher highest highland
highlight highlighted highlights highly highs highway highways hiking hills hilton himself hindu
hints hired hiring hispanic historic historical history hitachi hitting hobbies hobby hockey holdem
holder holders holding holdings holds holes holiday holidays holland hollow holly hollywood holmes
holocaust homeland homeless homepage homes hometown homework honda honduras honest honey honolulu
honor honors hoped hopefully hopes hoping hopkins horizon horizontal hormone horny horrible horror
horse horses hospital hospitality hospitals hosted hostel hostels hosting hosts hotel hotels
hotelscom hotmail hottest hourly hours house household households houses housewares housewives
housing houston howard however howto hudson hughes human humanitarian humanities humanity humans
humidity humor hundred hundreds hungarian hungary hunger hungry hunter hunting huntington hurricane
husband hybrid hydraulic hydrocodone hydrogen hygiene hypothesis hypothetical hyundai iceland icons
idaho ideal ideas identical identification identified identifier identifies identify identifying
identity ignore ignored illegal illinois illness illustrated illustration illustrations image images
imagination imagine imaging immediate immediately immigrants immigration immune immunology impact
impacts impaired imperial implement implementation implemented implementing implications implied
implies import importance important importantly imported imports impose imposed impossible impressed
impression impressive improve improved improvement improvements improving inappropriate inbox
incentive incentives incest inches incidence incident incidents include included includes including
inclusion inclusive income incoming incomplete incorporate incorporated incorrect increase increased
increases increasing increasingly incredible incurred indeed independence independent independently
index indexed indexes india indian indiana indianapolis indians indicate indicated indicates
indicating indication indicator indicators indices indie indigenous indirect individual individually
individuals indonesia indonesian indoor induced induction industrial industries industry inexpensive
infant infants infected infection infections infectious infinite inflation influence influenced
influences inform informal information informational informative informed infrared infrastructure
ingredients inherited initial initially initiated initiative initiatives injection injured injuries
injury inkjet inline inner innocent innovation innovations innovative input inputs inquire inquiries
inquiry insects insert inserted insertion inside insider insight insights inspection inspections
inspector inspiration inspired install installation installations installed installing instance
instances instant instantly instead institute institutes institution institutional institutions
instruction instructional instructions instructor instructors instrument instrumental
instrumentation instruments insulin insurance insured intake integer integral integrate integrated
integrating integration integrity intel intellectual intelligence intelligent intend intended
intense intensity intensive intent intention inter interact interaction interactions interactive
interest interested interesting interests interface interfaces interference interim interior
intermediate internal international internationally internet internship interpretation interpreted
interracial intersection interstate interval intervals intervention interventions interview
interviews intimate intranet intro introduce introduced introduces introducing introduction
introductory invalid invasion invention inventory invest investigate investigated investigation
investigations investigator investigators investing investment investments investor investors
invisible invision invitation invitations invite invited invoice involve involved involvement
involves involving iraqi ireland irish irrigation isaac islam islamic island islands isolated
isolation israel israeli issue issued issues istanbul italia italian italiano italic italy items
itself itunes ivory jacket jackets jackie jackson jacksonville jacob jaguar jamaica james jamie
janet january japan japanese jason javascript jeans jefferson jeffrey jelsoft jennifer jenny jeremy
jerry jersey jerusalem jesse jessica jesus jewel jewellery jewelry jewish jimmy johnny johns johnson
johnston joined joining joins joint jokes jonathan jones jordan joseph joshua journal journalism
journalist journalists journals journey joyce judge judges judgment judicial juice julia julian
julie jumping junction jungle junior jurisdiction justice justify justin juvenile kansas karaoke
karen karma kathy katie katrina kazakhstan keeping keeps keith kelkoo kelly kennedy kenneth kenny
kentucky kenya kernel kerry kevin keyboard keyboards keyword keywords kidney kijiji killed killer
killing kills kilometers kinase kinda kinds kingdom kings kingston kissing kitchen kitty klein knife
knight knights knitting knives knock knowing knowledge knowledgestorm known knows kodak korea korean
kruger kuwait label labeled labels labor laboratories laboratory labour ladder laden ladies
lafayette lakes lambda lamps lancaster lance landing lands landscape landscapes lanes language
languages lanka laptop laptops large largely larger largest larry laser lasting lately later latest
latex latin latina latinas latino latitude latter latvia lauderdale laugh laughing launch launched
launches laundry laura lauren lawrence lawsuit lawyer lawyers layer layers layout leader leaders
leadership leading leads league learn learned learners learning lease leasing least leather leave
leaves leaving lebanon lecture lectures leeds legacy legal legally legend legendary legends
legislation legislative legislature legitimate leisure lemon lender lenders lending length lenses
leonard leone lesbian lesbians leslie lesser lesson lessons letter letters letting level levels
levitra lewis lexington lexmark lexus liabilities liability liable liberal liberia liberty librarian
libraries library licence license licensed licenses licensing licking liechtenstein lifestyle
lifetime light lighter lighting lightning lights lightweight liked likelihood likely likes likewise
limit limitation limitations limited limiting limits limousines lincoln linda lindsay linear lined
lines lingerie linked linking links linux lions liquid listed listen listening listing listings
listprice lists literacy literally literary literature lithuania litigation little livecam lived
liver liverpool lives livesex livestock living lloyd loaded loading loads loans lobby local locale
locally locate located location locations locator locked locking locks lodge lodging logan logged
logging logic logical login logistics logitech logos lolita london lonely longer longest longitude
looked looking looks looksmart lookup loops loose lopez losing losses lottery lotus louis louise
louisiana louisville lounge loved lovely lover lovers loves loving lower lowest lucas lucia lucky
luggage lunch luther luxembourg luxury lycos lying lyric lyrics macedonia machine machinery machines
macintosh macro macromedia madagascar madison madness madonna madrid magazine magazines magic
magical magnet magnetic magnificent magnitude maiden mailed mailing mailman mails mailto maine
mainland mainly mainstream maintain maintained maintaining maintains maintenance major majority
maker makers makes makeup making malawi malaysia maldives males malpractice malta mambo manage
managed management manager managers managing manchester mandate mandatory manga manhattan manitoba
manner manor manual manually manuals manufacture manufactured manufacturer manufacturers
manufacturing maple mapping marathon marble march marco marcus mardi margaret margin maria mariah
marie marijuana marilyn marina marine mario marion maritime marked marker markers market marketing
marketplace markets marking marks marriage married marriott marshall martha martial martin marvel
maryland mason massachusetts massage massive master mastercard masters masturbating masturbation
match matched matches matching material materials maternity mathematical mathematics mating matrix
matter matters matthew mattress mature mauritius maximize maximum maybe mayor mazda mcdonald meals
meaning meaningful means meant meanwhile measure measured measurement measurements measures
measuring mechanical mechanics mechanism mechanisms medal media median medicaid medical medicare
medication medications medicine medicines medieval meditation mediterranean medium medline meeting
meetings meets meetup melbourne melissa member members membership membrane memorabilia memorial
memories memory memphis mental mention mentioned mentor menus mercedes merchandise merchant
merchants mercury mercy merely merge merger merit merry message messages messaging messenger
metabolism metadata metal metallic metallica metals meter meters method methodology methods metres
metric metro metropolitan mexican mexico meyer miami michael michel michelle michigan micro
microphone microsoft microwave middle midlands midnight midwest might mighty migration milan mileage
miles milfhunter milfs military millennium miller million millions mills milton milwaukee minds
mineral minerals mines miniature minimal minimize minimum mining minister ministers ministries
ministry minneapolis minnesota minolta minor minority minus minute minutes miracle mirror mirrors
miscellaneous missed missile missing mission missions mississippi missouri mistake mistakes mistress
mitchell mitsubishi mixed mixer mixing mixture mobile mobiles mobility model modeling modelling
models modem modems moderate moderator moderators modern modes modification modifications modified
modify modular module modules moisture moldova molecular molecules moment moments momentum monaco
monday monetary money mongolia monica monitor monitored monitoring monitors monkey monroe monster
montana monte montgomery month monthly months montreal moore moral moreover morgan morning morocco
morris morrison mortality mortgage mortgages moscow moses mostly motel motels mother motherboard
mothers motion motivated motivation motor motorcycle motorcycles motorola motors mount mountain
mountains mounted mounting mounts mouse mouth moved movement movements movers moves movie movies
moving mozambique mozilla mpegs msgid msgstr multi multimedia multiple mumbai munich municipal
municipality murder murphy murray muscle muscles museum museums music musical musician musicians
muslim muslims mustang mutual myanmar myers myrtle myself mysimon myspace mysql mysterious mystery
nails naked named namely names namespace namibia nancy naples narrative narrow nascar nasdaq
nashville nasty nathan nation national nationally nations nationwide native natural naturally
naturals nature naughty naval navigate navigation navigator nearby nearest nearly nebraska
necessarily necessary necessity necklace needed needle needs negative negotiation negotiations
neighbor neighborhood neighbors neither nelson nepal nerve nervous nested netherlands netscape
network networking networks neural neutral nevada never nevertheless newark newbie newcastle newer
newest newfoundland newly newport newscom newsletter newsletters newspaper newspapers newton nextel
niagara nicaragua nicholas nickel nickname nicole niger nigeria night nightlife nightmare nights
nikon nintendo nipple nipples nirvana nissan nitrogen noble nobody nodes noise nokia nominated
nomination nominations nonprofit norfolk normal normally norman north northeast northern northwest
norton norway norwegian notebook notebooks noted notes nothing notice noticed notices notification
notifications notified notify notion notre nottingham novel novels novelty november nowhere nuclear
nudist nudity number numbers numeric numerical numerous nurse nursery nurses nursing nutrition
nutritional nutten nvidia nylon oakland oasis obesity obituaries object objective objectives objects
obligation obligations observation observations observe observed observer obtain obtained obtaining
obvious obviously occasion occasional occasionally occasions occupation occupational occupations
occupied occur occurred occurrence occurring occurs ocean october offense offensive offer offered
offering offerings offers office officer officers offices official officially officials offline
offset offshore often oklahoma older oldest olive oliver olympic olympics olympus omaha omega
omissions ongoing onion online ontario opened opening openings opens opera operate operated operates
operating operation operational operations operator operators opinion opinions opponent opponents
opportunities opportunity opposed opposite opposition optical optics optimal optimization optimize
optimum option optional options oracle orange orbit orchestra order ordered ordering orders
ordinance ordinary oregon organ organic organisation organisations organised organisms organization
organizational organizations organize organized organizer organizing orgasm oriental orientation
oriented origin original originally origins orlando orleans oscar other others otherwise ottawa
ought ourselves outcome outcomes outdoor outdoors outer outlet outline outlined outlook output
outputs outreach outside outsourcing outstanding overall overcome overhead overnight overseas
overview owned owner owners ownership oxford oxide oxygen ozone pacific package packages packaging
packard packed packet packets packing packs pages painful paint paintball painted painting paintings
pairs pakistan palace palestine palestinian palmer pamela panama panasonic panel panels panic
panties pants pantyhose paper paperback paperbacks papers papua parade paradise paragraph paragraphs
paraguay parallel parameter parameters parcel parent parental parenting parents paris parish parker
parking parks parliament parliamentary partial partially participant participants participate
participated participating participation particle particles particular particularly parties
partition partly partner partners partnership partnerships parts party passage passed passenger
passengers passes passing passion passive passport password passwords pasta paste pastor patch
patches patent patents pathology paths patient patients patio patricia patrick patrol pattern
patterns pavilion paxil payable payday paying payment payments paypal payroll peace peaceful pearl
pediatric peeing peers penalties penalty pencil pendant pending penetration penguin peninsula penis
pennsylvania penny pension pensions pentium people peoples pepper perceived percent percentage
perception perfect perfectly perform performance performances performed performer performing
performs perfume perhaps period periodic periodically periods peripheral peripherals permalink
permanent permission permissions permit permits permitted perry persian persistent person personal
personality personalized personally personals personnel persons perspective perspectives perth peter
petersburg peterson petite petition petroleum phantom pharmaceutical pharmaceuticals pharmacies
pharmacology pharmacy phase phases phenomenon phentermine philadelphia philip philippines philips
phillips philosophy phoenix phone phones photo photograph photographer photographers photographic
photographs photography photos photoshop phpbb phrase phrases physical physically physician
physicians physics physiology piano pichunter picked picking picks pickup picnic picture pictures
piece pieces pierce pierre pillow pills pilot pioneer pipeline pipes pirates pissing pitch
pittsburgh pixel pixels pizza place placed placement places placing plain plains plaintiff plane
planes planet planets planned planner planners planning plans plant plants plasma plastic plastics
plate plates platform platforms platinum playback playboy played player players playing playlist
plays playstation plaza pleasant please pleased pleasure pledge plenty plots plugin plugins plumbing
plymouth pocket pockets podcast podcasts poems poetry point pointed pointer pointing points pokemon
poker poland polar police policies policy polish polished political politicians politics polls
pollution polyester polymer polyphonic pontiac pools popular popularity population populations
porcelain porno porsche portable portal porter portfolio portion portions portland portrait
portraits ports portsmouth portugal portuguese posing position positioning positions positive
possess possession possibilities possibility possible possibly postage postal postcard postcards
posted poster posters posting postings postposted posts potato potatoes potential potentially potter
pottery poultry pound pounds poverty powder powell power powered powerful powerpoint powers
powerseller practical practice practices practitioner practitioners prague prairie praise prayer
prayers preceding precious precipitation precise precisely precision predict predicted prediction
predictions prefer preference preferences preferred prefers prefix pregnancy pregnant preliminary
premier premiere premises premium prepaid preparation prepare prepared preparing prerequisite
prescribed prescription presence present presentation presentations presented presenting presently
presents preservation preserve president presidential press pressed pressing pressure preston pretty
prevent preventing prevention preview previews previous previously price priced prices pricing pride
priest primarily primary prime prince princess princeton principal principle principles print
printable printed printer printers printing prints prior priorities priority prison prisoner
prisoners privacy private privilege privileges prize prizes probability probably probe problem
problems procedure procedures proceed proceeding proceedings proceeds process processed processes
processing processor processors procurement produce produced producer producers produces producing
product production productions productive productivity products profession professional
professionals professor profile profiles profit profits program programme programmer programmers
programmes programming programs progress progressive prohibited project projected projection
projector projectors projects prominent promise promised promises promising promo promote promoted
promotes promoting promotion promotional promotions prompt promptly proof propecia proper properly
properties property prophet proportion proposal proposals propose proposed proposition proprietary
prospect prospective prospects prostate prostores protect protected protecting protection protective
protein proteins protest protocol protocols prototype proud proudly prove proved proven provide
provided providence provider providers provides providing province provinces provincial provision
provisions proxy prozac psychiatry psychological psychology public publication publications
publicity publicly publish published publisher publishers publishing pubmed puerto pulled pulling
pulse pumps punch punishment pupils puppy purchase purchased purchases purchasing purple purpose
purposes purse pursuant pursue pursuit pushed pushing pussy putting puzzle puzzles python qatar
qualification qualifications qualified qualify qualifying qualities quality quantitative quantities
quantity quantum quarter quarterly quarters quebec queen queens queensland queries query quest
question questionnaire questions queue quick quickly quiet quilt quite quizzes quotations quote
quoted quotes rabbit races rachel racial racing racks radar radiation radical radio radios radius
railroad railway rainbow raise raised raises raising raleigh rally ralph ranch random randy range
rangers ranges ranging ranked ranking rankings ranks rapid rapidly rapids rarely rated rates rather
rating ratings ratio rational ratios raymond reach reached reaches reaching reaction reactions
reader readers readily reading readings reads ready realistic reality realize realized really realm
realtor realtors realty reason reasonable reasonably reasoning reasons rebate rebates rebecca rebel
rebound recall receipt receive received receiver receivers receives receiving recent recently
reception receptor receptors recipe recipes recipient recipients recognised recognition recognize
recognized recommend recommendation recommendations recommended recommends reconstruction record
recorded recorder recorders recording recordings records recover recovered recovery recreation
recreational recruiting recruitment recycling redeem redhead reduce reduced reduces reducing
reduction reductions refer reference referenced references referral referrals referred referring
refers refinance refine refined reflect reflected reflection reflections reflects reform reforms
refresh refrigerator refugees refund refurbished refuse refused regard regarded regarding regardless
regards reggae regime region regional regions register registered registrar registration registry
regression regular regularly regulated regulation regulations regulatory rehab rehabilitation reject
rejected relate related relates relating relation relations relationship relationships relative
relatively relatives relax relaxation relay release released releases relevance relevant reliability
reliable reliance relief religion religions religious reload relocation relying remain remainder
remained remaining remains remark remarkable remarks remedies remedy remember remembered remind
reminder remix remote removable removal remove removed removing renaissance render rendered
rendering renew renewable renewal rental rentals rentcom repair repairs repeat repeated replace
replaced replacement replacing replica replication replied replies reply report reported reporter
reporters reporting reports repository represent representation representations representative
representatives represented representing represents reprint reprints reproduce reproduced
reproduction reproductive republic republican republicans reputation request requested requesting
requests require required requirement requirements requires requiring rescue research researcher
researchers reseller reservation reservations reserve reserved reserves reservoir reset residence
resident residential residents resist resistance resistant resolution resolutions resolve resolved
resort resorts resource resources respect respected respective respectively respiratory respond
responded respondent respondents responding response responses responsibilities responsibility
responsible restaurant restaurants restoration restore restored restrict restricted restriction
restrictions restructuring result resulted resulting results resume resumes retail retailer
retailers retain retained retention retired retirement retreat retrieval retrieve retrieved retro
return returned returning returns reunion reuters reveal revealed reveals revelation revenge revenue
revenues reverse review reviewed reviewer reviewing reviews revised revision revisions revolution
revolutionary reward rewards reynolds rhode rhythm ribbon richard richards richardson richmond rider
riders rides ridge riding right rights rings ringtone ringtones rising risks river rivers riverside
roads robert roberts robertson robin robinson robot robots robust rochester rocket rocks rocky roger
rogers roland roles rolled roller rolling rolls roman romance romania romantic ronald roommate
roommates rooms roots roses roster rotary rotation rouge rough roughly roulette round rounds route
router routers routes routine routines routing rover royal royalty rubber rugby ruled rules ruling
runner running runtime rural russell russia russian rwanda sacramento sacred sacrifice saddam safari
safely safer safety sagem sailing saint saints salad salaries salary salem sales sally salmon salon
salvador salvation samba samoa sample samples sampling samsung samuel sandra sandwich sandy santa
sanyo sapphire sarah saskatchewan satellite satin satisfaction satisfactory satisfied satisfy
saturday saturn sauce saudi savage savannah saved saver saves saving savings saying sbjct scale
scales scanned scanner scanners scanning scary scenario scenarios scene scenes scenic schedule
scheduled schedules scheduling schema scheme schemes scholar scholars scholarship scholarships
school schools science sciences scientific scientist scientists scoop scope score scored scores
scoring scotia scotland scott scottish scout scratch screen screening screens screensaver
screensavers screenshot screenshots screw script scripting scripts scroll scuba sculpture seafood
sealed search searchcom searched searches searching season seasonal seasons seating seats seattle
second secondary seconds secret secretariat secretary secrets section sections sector sectors secure
secured securely securities security seeds seeing seeker seekers seeking seeks seemed seems segment
segments select selected selecting selection selections selective seller sellers selling sells
semester semiconductor seminar seminars senate senator senators sender sending sends senegal senior
seniors sense sensitive sensitivity sensor sensors sentence sentences separate separated separately
separation september sequence sequences serbia serial series serious seriously serum serve served
server servers serves service services serving session sessions setting settings settle settled
settlement setup seven seventh several severe sewing sexcam sexual sexuality sexually shade shades
shadow shadows shaft shake shakespeare shakira shall shame shanghai shannon shape shaped shapes
share shared shareholders shares shareware sharing shark sharon sharp shaved sheep sheer sheet
sheets sheffield shelf shell shelter shemale shemales shepherd sheriff sherman shield shift shine
shipment shipments shipped shipping ships shirt shirts shock shoes shoot shooting shopper shoppercom
shoppers shopping shoppingcom shops shopzilla shore short shortcuts shorter shortly shorts shots
should shoulder showcase showed shower showers showing shown shows showtimes shuttle sides siemens
sierra sight sigma signal signals signature signatures signed significance significant significantly
signing signs signup silence silent silicon silly silver similar similarly simon simple simplified
simply simpson simpsons simulation simulations simultaneously since singapore singer singh singing
single singles sister sisters sitemap sites sitting situated situation situations sixth sized sizes
skating skiing skill skilled skills skins skirt skirts skype slave sleep sleeping sleeps sleeve
slide slides slideshow slight slightly slope slots slovak slovakia slovenia slowly sluts small
smaller smart smell smile smilies smith smithsonian smoke smoking smooth snake snapshot snowboard
soccer social societies society sociology socket socks sodium softball software solar solaris
soldier soldiers solely solid solomon solution solutions solve solved solving somalia somebody
somehow someone somerset something sometimes somewhat somewhere songs sonic soonest sophisticated
sorry sorted sorts sought souls sound sounds soundtrack source sources south southampton southeast
southern southwest soviet space spaces spain spanish spank spanking sparc spare spatial speak
speaker speakers speaking speaks spears special specialist specialists specialized specializing
specially specials specialties specialty species specific specifically specification specifications
specifics specified specifies specify specs spectacular spectrum speech speeches speed speeds spell
spelling spencer spend spending spent sperm sphere spice spider spies spine spirit spirits spiritual
spirituality split spoke spoken spokesman sponsor sponsored sponsors sponsorship sport sporting
sports spotlight spots spouse spray spread spreading spring springer springfield springs sprint
spyware squad square squirt squirting stability stable stack stadium staff staffing stage stages
stainless stakeholders stamp stamps stand standard standards standing standings stands stanford
stanley starring stars starsmerchant start started starter starting starts startup state stated
statement statements states statewide static stating station stationery stations statistical
statistics stats status statute statutes statutory stayed staying stays steady steal steam steel
steering stephanie stephen steps stereo sterling steve steven stevens stewart stick sticker stickers
sticks sticky still stock stockholm stockings stocks stolen stomach stone stones stood stopped
stopping stops storage store stored stores stories storm story straight strain strand strange
stranger strap strategic strategies strategy stream streaming streams street streets strength
strengthen strengthening strengths stress stretch strict strictly strike strikes striking string
strings strip stripes strips stroke strong stronger strongly struck struct structural structure
structured structures struggle stuart stuck student students studied studies studio studios study
studying stuff stuffed stunning stupid style styles stylish stylus subaru subcommittee subdivision
subject subjects sublime sublimedirectory submission submissions submit submitted submitting
subscribe subscriber subscribers subscription subscriptions subsection subsequent subsequently
subsidiaries subsidiary substance substances substantial substantially substitute subtle suburban
succeed success successful successfully sucking sucks sudan sudden suddenly suffer suffered
suffering sufficient sufficiently sugar suggest suggested suggesting suggestion suggestions suggests
suicide suitable suite suited suites suits sullivan summaries summary summer summit sunday
sunglasses sunny sunrise sunset sunshine super superb superintendent superior supervision supervisor
supervisors supplement supplemental supplements supplied supplier suppliers supplies supply support
supported supporters supporting supports suppose supposed supreme surely surface surfaces surfing
surge surgeon surgeons surgery surgical surname surplus surprise surprised surprising surrey
surround surrounded surrounding surveillance survey surveys survival survive survivor survivors
susan suspect suspected suspended suspension sussex sustainability sustainable sustained suzuki
sweden swedish sweet swift swimming swing swingers swiss switch switched switches switching
switzerland sword sydney symantec symbol symbols sympathy symphony symposium symptoms syndicate
syndication syndrome synopsis syntax synthesis synthetic syracuse syria system systematic systems
table tables tablet tablets tackle tactics tagged tahoe taiwan taken takes taking talent talented
tales talked talking talks tamil tampa tanks tanzania tapes target targeted targets tariff tasks
taste tattoo taught taxation taxes taylor teach teacher teachers teaches teaching teams tears
technical technician technique techniques techno technological technologies technology techrepublic
teddy teenage teens teeth telecharger telecom telecommunications telephone telephony telescope
television televisions telling tells temperature temperatures template templates temple temporal
temporarily temporary tenant tender tennessee tennis tension terminal terminals termination
terminology terms terrace terrain terrible territories territory terror terrorism terrorist
terrorists terry testament tested testimonials testimony testing tests texas textbook textbooks
textile textiles texts texture thailand thank thanks thanksgiving thats theater theaters theatre
theft thehun their theme themes themselves theology theorem theoretical theories theory therapeutic
therapist therapy there thereafter thereby therefore thereof thermal thesaurus these thesis thick
thickness thing things think thinking thinkpad thinks third thirty thomas thompson thomson thong
thongs thorough thoroughly those though thought thoughts thousand thousands thread threaded threads
threat threatened threatening threats three threesome threshold thriller throat through throughout
throw throwing thrown throws thumb thumbnail thumbnails thumbs thumbzilla thunder thursday ticket
tickets tiffany tiger tigers tight tiles timber timeline timely timer times timing timothy tions
tired tires tissue titanium titans title titled titles titten tobacco tobago today toddler together
toilet token tokyo tolerance tomato tomatoes tommy tomorrow toner tones tongue tonight toolbar
toolbox toolkit tools tooth topic topics topless toronto torture toshiba total totally totals touch
touched tough touring tourism tourist tournament tournaments tours toward towards tower towers towns
township toxic toyota trace track trackback trackbacks tracked tracker tracking tracks tract tractor
tracy trade trademark trademarks trader trades trading tradition traditional traditions traffic
tragedy trail trailer trailers trails train trained trainer trainers training trains tramadol trance
tranny trans transaction transactions transcript transcription transcripts transexual transexuales
transfer transferred transfers transform transformation transit transition translate translated
translation translations translator transmission transmit transmitted transparency transparent
transport transportation transsexual trash trauma travel traveler travelers traveling traveller
travelling travels travesti travis treasure treasurer treasures treasury treat treated treating
treatment treatments treaty trees trembl tremendous trend trends trial trials triangle tribal tribe
tribes tribunal tribune tribute trick tricks tried tries trigger trinidad trinity tripadvisor triple
trips triumph trivia troops tropical trouble troubleshooting trout truck trucks truly trunk trust
trusted trustee trustees trusts truth trying tsunami tubes tucson tuesday tuition tulsa tumor tuner
tunes tuning tunisia tunnel turbo turkey turkish turned turner turning turns turtle tutorial
tutorials tvcom twelve twenty twice twiki twinks twins twist twisted tyler types typical typically
typing uganda ukraine ultimate ultimately ultra ultram unable unauthorized unavailable uncertainty
uncle undefined under undergraduate underground underlying understand understanding understood
undertake undertaken underwear unemployment unexpected unfortunately unified uniform union unions
uniprotkb unique united units unity universal universe universities university unknown unless unlike
unlikely unlimited unlock unnecessary unsigned unsubscribe until untitled unusual unwrap upcoming
update updated updates updating upgrade upgrades upgrading upload uploaded upper upset upskirt
upskirts urban urgent uruguay usage useful username users using usual usually utilities utility
utilization utilize utils uzbekistan vacancies vacation vacations vaccine vacuum vagina valentine
valid validation validity valium valley valuable valuation value valued values valve valves vampire
vancouver vanilla variable variables variance variation variations varied varies variety various
varying vatican vault vbulletin vector vegas vegetable vegetables vegetarian vegetation vehicle
vehicles velocity velvet vendor vendors venezuela venice venture ventures venue venues verbal verde
verification verified verify verizon vermont vernon verse version versions versus vertex vertical
verzeichnis vessel vessels veteran veterans veterinary viagra vibrator vibrators victim victims
victor victoria victorian victory video videos vienna vietnam vietnamese viewed viewer viewers
viewing viewpicture views viking villa village villages villas vincent vintage vinyl violation
violations violence violent violin viral virgin virginia virtual virtually virtue virus viruses
visibility visible vision visit visited visiting visitor visitors visits vista visual vital vitamin
vitamins vocabulary vocal vocals vocational voice voices volkswagen volleyball voltage volume
volumes voluntary volunteer volunteers volvo voted voters votes voting voyeur voyeurweb voyuer vsnet
vulnerability vulnerable wages wagner wagon waiting waiver wales walked walker walking walks wallace
wallet wallpaper wallpapers walls walnut walter wanna wanted wanting wants warcraft warehouse
warming warned warner warning warnings warrant warranties warranty warren warrior warriors washer
washing washington waste watch watched watches watching water waterproof waters watershed watson
watts waves wayne wealth weapon weapons wearing weather webcam webcams webcast weblog weblogs
webmaster webmasters webpage webshots website websites webster wedding weddings wednesday weekend
weekends weekly weeks weight weighted weights weird welcome welding welfare wellington wellness
wells welsh wendy wesley western westminster whale whatever whats wheat wheel wheels whenever where
whereas wherever whether which while whilst white whole wholesale whore whose wichita wicked widely
wider widescreen widespread width wikipedia wilderness wildlife wiley william williams willing
willow wilson window windows winds windsor wines wings winner winners winning winston winter wired
wireless wires wiring wisconsin wisdom wishes wishlist witch withdrawal within without witness
witnesses wives wizard woman women womens wonder wonderful wondering wooden woods worcester
wordpress words worked worker workers workflow workforce working workout workplace works workshop
workshops workstation world worldcat worlds worldsex worldwide worried worry worse worship worst
worth worthy would wound wrapped wrapping wrestling wright wrist write writer writers writes writing
writings written wrong wrote wyoming xanax xerox xhtml yacht yahoo yamaha yards yearly years yeast
yellow yemen yesterday yield yields yorkshire young younger yours yourself youth yugoslavia yukon'''

####dammed data####
data='''
c2MAAZpvEl5yExy1MWx9uXwe8tFf5bSwuPwYhg/Xgaq41dDilfjgAQE27WV5gcr7DC7u3OU8Adba
jO3hAuI33H/3ArKIUPAgQDAzDbR4t/yrJeTW1V+FNHZKF+zVsM+3xgtRXsitkxsPkOlRc5Q=
'''
####dammed data####

if __name__ == '__main__':
	main(argv[1] if len(argv) > 1 else None)
